# Generated by Django 3.1.3 on 2020-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='std_registration_form',
            fields=[
                ('student_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('admission_no', models.IntegerField()),
                ('date_of_admission_in_this_school', models.DateField()),
                ('CID', models.CharField(blank=True, max_length=11)),
                ('class_teacher', models.CharField(max_length=30)),
                ('previous_school', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=8)),
                ('permanent_address', models.TextField()),
                ('BoarderOrDayscholar', models.CharField(choices=[('Boarder', 'Boarder'), ('Dayscholar', 'Dayscholar')], max_length=30)),
                ('RegularOrRepeater', models.CharField(choices=[('Regular', 'Regular'), ('Repeater', 'Repeater')], max_length=30)),
                ('profile_pic', models.ImageField(upload_to='images/students')),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('fathers_occupation', models.CharField(max_length=50)),
                ('mothers_occupation', models.CharField(max_length=50)),
                ('parents_mobile_number', models.CharField(max_length=8)),
            ],
        ),
    ]
