# Generated by Django 3.1.3 on 2020-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='BoarderOrDayscholar',
            field=models.CharField(blank=True, choices=[('Boarder', 'Boarder'), ('Dayscholar', 'Dayscholar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='RegularOrRepeater',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Repeater', 'Repeater')], max_length=30),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='class_teacher',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='date_of_admission_in_this_school',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='father_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='fathers_occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='mothers_occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='parents_mobile_number',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='previous_school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/students'),
        ),
    ]
