# Generated by Django 3.1.3 on 2020-12-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201201_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='std_registration_form',
            name='BoarderOrDayscholar',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='CID',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='RegularOrRepeater',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='admission_no',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='date_of_admission_in_this_school',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='fathers_occupation',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='mothers_occupation',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='parents_mobile_number',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='std_registration_form',
            name='profile_pic',
        ),
    ]
