# Generated by Django 3.1.3 on 2020-12-01 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201201_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_registration_form',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
