# Generated by Django 3.1.3 on 2020-12-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20201201_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_registration_form',
            name='class_teacher',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='std_registration_form',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='std_registration_form',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='std_registration_form',
            name='previous_school',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
