# Generated by Django 3.1.3 on 2020-12-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20201201_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_registration_form',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/students'),
        ),
    ]
