# Generated by Django 3.1.3 on 2020-12-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20201201_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='profile_pic',
            field=models.ImageField(upload_to='images/students'),
        ),
    ]
