# Generated by Django 3.1.3 on 2020-12-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20201204_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/user.jpg', null=True, upload_to='images/students'),
        ),
    ]
