# Generated by Django 3.1.3 on 2020-12-07 13:25

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20201205_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std_registration_form',
            old_name='date_of_admission_in_this_school',
            new_name='date_of_admission',
        ),
        migrations.AddField(
            model_name='std_registration_form',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='CID',
            field=models.CharField(blank=True, default='124', max_length=11, validators=[students.validators.validate_cid]),
        ),
    ]
