# Generated by Django 3.1.3 on 2020-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20201207_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='CID',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='admission_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='date_of_admission',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='section',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='standard',
            field=models.IntegerField(blank=True),
        ),
    ]
