# Generated by Django 3.1.2 on 2020-12-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20201208_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='std_registration_form',
            options={'ordering': ['section']},
        ),
    ]
