# Generated by Django 3.1.2 on 2020-12-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20201210_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='std_registration_form',
            options={},
        ),
    ]
