# Generated by Django 3.1.2 on 2020-12-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20201215_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='CID',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
