# Generated by Django 3.1.2 on 2020-12-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20201215_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30),
        ),
        migrations.CreateModel(
            name='DisciplinaryIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Violation_detail', models.TextField()),
                ('Violation_date', models.DateField()),
                ('Warning_decision', models.TextField()),
                ('Approved_by', models.CharField(max_length=50)),
                ('Student_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.std_registration_form')),
            ],
        ),
    ]
