# Generated by Django 3.1.2 on 2020-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20201216_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryissue',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
