# Generated by Django 3.1.2 on 2020-12-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20201217_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinaryissue',
            name='Student_code',
        ),
        migrations.AddField(
            model_name='disciplinaryissue',
            name='Student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.std_registration_form'),
        ),
    ]
