# Generated by Django 3.1.2 on 2020-12-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20201217_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryissue',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.std_registration_form'),
        ),
    ]
