# Generated by Django 3.1.2 on 2020-12-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_auto_20201217_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Volunteerism', 'Volunteerism'), ('Volunteerism', 'Volunteerism'), ('Academic', 'Academic'), ('Games and Sports', 'Games and Sports'), ('Literary', 'Literary'), ('Cultural', 'Cultural')], max_length=30)),
                ('Description', models.TextField()),
                ('Awarded_on', models.DateField()),
                ('Awarded_by', models.CharField(max_length=100)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.std_registration_form')),
            ],
        ),
    ]
