# Generated by Django 3.1.2 on 2020-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20201222_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercertificate',
            name='Category',
            field=models.CharField(choices=[('Special_Recognition', 'Special_Recognition'), ('Volunteerism', 'Volunteerism'), ('Academic', 'Academic'), ('Games and Sports', 'Games and Sports'), ('Literary', 'Literary'), ('Cultural', 'Cultural')], max_length=30),
        ),
    ]
