# Generated by Django 3.1.2 on 2020-12-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_auto_20201222_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='student_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
