# Generated by Django 3.1.2 on 2020-12-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_std_registration_form_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=30),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='standard',
            field=models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=30),
        ),
    ]
