# Generated by Django 3.1.2 on 2020-12-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_auto_20201225_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercertificate',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.std_registration_form'),
        ),
        migrations.AlterField(
            model_name='disciplinaryissue',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.std_registration_form'),
        ),
        migrations.AlterField(
            model_name='std_registration_form',
            name='class_teacher',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
