# Generated by Django 3.1.2 on 2020-12-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_auto_20201225_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='class_teacher',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
