# Generated by Django 3.1.2 on 2020-12-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20201225_2001'),
        ('students', '0034_auto_20201225_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_registration_form',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffdetail'),
        ),
    ]
