# Generated by Django 3.1.2 on 2020-12-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffDetails',
            new_name='StaffDetail',
        ),
    ]
